# Importing 'numpy' package

In [1]:
import numpy as np

# Array Attributes

In [2]:
arr = np.array([1, 2, 3, 4])      # creating a 1-D array (1-D arrays are called VECTOR) (D=dimension)

In [3]:
arr                               # accessing the array

array([1, 2, 3, 4])

In [4]:
type(arr)                         # checking the array type

numpy.ndarray

In [5]:
arr.dtype                         # checking the array data type

dtype('int32')

In [6]:
arr.size                          # checking the total number of elements in the array

4

In [7]:
arr.shape                         # checkhing the array shape

(4,)

In [8]:
arr.ndim                          # checking the array dimension

1

## Array more than 1-D (like the 2-D and 3-D) is called MATRIX

In [9]:
brr = np.array([[1, 2, 3],[4, 5.8, 6]])         # creating a 2-D array

In [10]:
brr                                            

array([[1. , 2. , 3. ],
       [4. , 5.8, 6. ]])

In [11]:
brr.dtype                      

dtype('float64')

In [12]:
brr.size

6

In [13]:
brr.shape

(2, 3)

In [14]:
brr.ndim

2

In [15]:
crr = np.array([[[1, 2, 3, 4],                   # creating a 3-D array
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]]])       

In [16]:
print(crr)                                       # printing the array 

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [17]:
crr.shape                                   

(1, 3, 4)

In [18]:
crr.ndim                                   

3

In [19]:
crr.size                                  

12

# Array Creation

In [20]:
array1 = np.array([1, 2, 3], dtype = 'int')          # 'dtype' for specifying the data type

In [21]:
array1                                               # accessing the array

array([1, 2, 3])

In [22]:
array2 = np.zeros((2,3), dtype = 'int')
 # to see any built-in array's properties (like the properties of 
                                     #'zeros') press 'shift+tab' after typing 'np.zeros()'

In [23]:
array2

array([[0, 0, 0],
       [0, 0, 0]])

In [24]:
array3 = np.ones((3,3), dtype = 'float')

In [25]:
array3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
array4 = np.full((2,3), 5)               # a 2 x 3 matrix constructed with the number 5 only

In [27]:
array4

array([[5, 5, 5],
       [5, 5, 5]])

In [28]:
array5 = np.identity((4), dtype = 'int') # Identity matrix: a matrix with equal no. of row and column 

In [29]:
array5

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [30]:
array6 = np.arange(2, 20, 2)             # from 2 to (upto) 20 with a gradual increasing of 2       

In [31]:
array6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
array7 = np.linspace(1, 2, 20)           # creating 20 values within 1 to 2

In [33]:
array7

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

# INDEXING

# indexing of 1-D array

In [34]:
array1 = np.array([5, 6, 7, 8, 9])

In [35]:
print (array1)

[5 6 7 8 9]


In [36]:
array1[0]          # accessinng the FIRST element of the array using the 'INDEX VALUE'

5

In [37]:
array1[4]          # accessinng the LAST element of the array using the 'INDEX VALUE'

9

In [38]:
array1[-1]         # accessinng the LAST element of the array using the 'INDEX VALUE'

9

In [39]:
array1[-2]         # accessinng the SECOND LAST element of the array using the 'INDEX VALUE'

8

# indexing of 2-D array

In [40]:
array2 = np.random.randint(1, 10, size = (4,3)) # creating array with random integer values of a range 

In [41]:
print (array2)

[[9 3 6]
 [2 4 6]
 [2 3 6]
 [7 5 9]]


In [42]:
array2[0,0]         # accessing the FIRST element of a 2-D array        # [row index, column index]

9

In [43]:
array2[2,1]         # accessing the SECOND element of the THIRD row

3

# indexing of 3-D array

In [44]:
array3 = np.random.randint(1, 10, size = (2,3,3))

In [45]:
print (array3)

[[[1 8 1]
  [9 7 8]
  [8 9 1]]

 [[6 4 3]
  [3 3 2]
  [7 3 1]]]


In [46]:
array3[0,1,1]             # accessing the 8 of SECOND ROW of the SECOND COLUMN

7

In [47]:
array3[1,1,2]             # accessing the 3 of FIFTH ROW of the THIRD COLUMN

2

# SLICING

# slicing of 1-D array

In [48]:
array1 = np.array([9, 8, 7, 6, 5, 4])

In [49]:
print (array1)            # array1

[9 8 7 6 5 4]


In [50]:
array1[:3]                # slicing the array from STARTING through MIDWAY using the INDEX VALUE

array([9, 8, 7])

In [51]:
print (array1)            # array1

[9 8 7 6 5 4]


In [52]:
array1[1:4]               # slicing the array from 8 to 6 using the INDEX VALUE

array([8, 7, 6])

# slicing of 2-D array

In [53]:
array2 = np.random.randint(1, 10, size = (4,3))

In [54]:
print(array2)              # this is a 4 X 3 (read : 4 by 3) MATRIX   

[[2 6 7]
 [8 3 7]
 [6 8 5]
 [5 3 3]]


In [55]:
array2[0:2]                # slicing for FIRST TWO ROW only    # converting to a 2 x 3 MATRIX

array([[2, 6, 7],
       [8, 3, 7]])

In [56]:
array2[0:2, 0:2]           # slicing for FIRST TWO value of the FIRST TWO ROW only 

array([[2, 6],
       [8, 3]])

In [57]:
array2[1:, 1:]         

array([[3, 7],
       [8, 5],
       [3, 3]])

# Manipulating Array Shape

# reshape ( )

In [58]:
arr = np.array([[1, 2, 3],
               [3, 4, 5]])

In [59]:
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [60]:
arr.shape                  # checking the original shape of the array

(2, 3)

In [61]:
arr_reshaped = np.reshape(arr, (3,2))             # changing the original shape of the array

In [62]:
arr_reshaped

array([[1, 2],
       [3, 3],
       [4, 5]])

In [63]:
arr_reshaped.shape         # checking the changed shape 

(3, 2)

# resize ( )

In [64]:
br = np.array ([[3, 4, 5, 6],
               [1, 7, 8, 9]])

In [65]:
br                                      # 2 x 4 array

array([[3, 4, 5, 6],
       [1, 7, 8, 9]])

In [66]:
br_resized = np.resize (br, (4,4))

In [67]:
br_resized                 # resize method REPEATS the elements of the array to maintain the shape 

array([[3, 4, 5, 6],
       [1, 7, 8, 9],
       [3, 4, 5, 6],
       [1, 7, 8, 9]])

# ravel ( )

## this function converts any other dimensional (2-D, 3-D, etc.) array into a 1-D array and return a view of the original array

In [68]:
cr = np.random.randint (1, 6, (2, 3))

In [69]:
cr

array([[1, 2, 2],
       [5, 3, 2]])

In [70]:
cr_raveled = np.ravel(cr)

In [71]:
cr_raveled

array([1, 2, 2, 5, 3, 2])

# flatten ( )

## this function converts any other dimensional (2-D, 3-D, etc.) array into a 1-D array and return a copy of the original array and allocates a new memory

In [72]:
dr = np.random.randint (1, 6, (3, 4))

In [73]:
dr

array([[5, 5, 3, 1],
       [2, 2, 2, 3],
       [1, 5, 1, 2]])

In [74]:
dr_flattened = dr.flatten()

In [75]:
dr_flattened

array([5, 5, 3, 1, 2, 2, 2, 3, 1, 5, 1, 2])

# defining an array shape

## providing a new shape to change an existing shape

In [76]:
ar = np.array([[2, 3, 4], [5, 6, 7]])

In [77]:
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [78]:
arr.shape                 # checking the existing shape

(2, 3)

In [79]:
arr.shape = (3, 2)        # defining a new shape

In [80]:
arr

array([[1, 2],
       [3, 3],
       [4, 5]])

# Stacking 

## Horizontal stacking 

### hstack and column_stack do the same thing 

In [81]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [82]:
a                                # Array-'a'

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
b = 2*a                                         # multiplying the Array-'a' by 2 to create a new array

In [84]:
b                                # Array-'b'

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [85]:
c = np.hstack((a,b))

In [86]:
c                                       # 'a' and 'b' h-stacked  

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [87]:
c2 = np.column_stack((a,b))             # 'a' and 'b' column-stacked

In [88]:
c2

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [89]:
c3 = np.concatenate((a,b), axis = 1)    # horizontal stacking by concatenate function

In [90]:
c3

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

## Vertical stacking 

### vstack and row_stack do the same thing 

In [91]:
c4 = np.vstack((a, b))                      # 'a' and 'b' v-stacked

In [92]:
c4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [93]:
c5 = np.row_stack((a, b))                   # 'a' and 'b' row-stacked

In [94]:
c5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [95]:
c6 = np.concatenate((a,b), axis = 0)        # vertical stacking by concatenate function

In [96]:
c6

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# Depth stacking 

In [97]:
c7 = np.dstack((a, b))

In [98]:
c7                                          # 'a' and 'b' depth-stacked

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])